### ISSUE TITLE
Free events and videos

### ISSUE THREAD

**Issue by mgifford** [dwp/accessibility-manual#30]
This list of courses might be useful:
https://github.com/accessibility/a11y-courses

There is a lot of redundancy:
https://github.com/accessibility/a11y-lists-of-lists

If there is a way to point to other lists this can be helpful. Ultimately we need a community to maintain these ongoing activities. 

2 big events though:
https://globalaccessibilityawarenessday.org/
https://www.un.org/en/observances/day-of-persons-with-disabilities

**Comment by abbott567** [comment]
Thanks @mgifford will add these in the next release.

**Comment by abbott567** [comment]
Added a11y-courses and global accessibility awareness day in version 2.1.0. 
Due to one of the events being Dec 3rd I unfortunately missed the boat on that one as it took so long to make the updates. 

I  also didn't find an easy way to add a11y-lists as there wasn't a clear section for it. Closing this issue, but we should look at perhaps building some kind of API for all this stuff rather than duplicating or redirecting people to multiple lists.

Happy to collab on that, we can open a separate issue if it's something worth pursuing.

**Comment by mgifford** [comment]
Thanks @abbott567 - and ya, I like the idea of a GitHub based API...  That would be nice, but..  Even if you could just fork a page rather than a project..  Anyways, I'll circle back if something comes up.
