### ISSUE TITLE
Session Timeout - how long?

### ISSUE THREAD

**Issue by MacTheFork** [dwp/accessibility-manual#56]
https://accessibility-manual.dwp.gov.uk/guidance-for-your-job-role/software-engineer-or-frontend-developer
Timeouts section says
"the default time limit is set to at least 20 hours"

Shouldn't this be minutes, not hours?

**Comment by abbott567** [comment]
@MacTheFork no, 20 hours is correct. 

The content states 20 hours because that is the exception time outlined in the Web Content Accessibility Guidelines under [2.1.1 Timing Adjustable](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html). 

If you configure your application so that every session is automatically set to expire after 20 hours, then you don't need to do extra work to make the session extendable, you just pass the criterion. 

If it's less than 20 hours, like 20 minutes or even 1 hour, then you need to provide a way for the user to configure it.

**Comment by MacTheFork** [comment]
Thank you for your response which clarifies the matter.  The reference to [2.1.1 Timing Adjustable](https://www.w3.org/WAI/WCAG21/Understanding/timing-adjustable.html) was very helpful.
 
I had misunderstood the paragraph having not registered the 'one of' applying to the bullet points.  Consequently I was reading the bullet points in sequence with an implicit 'and' between them.  

May I suggest the phrase 'one of' is expanded to match the WCAG phrasing of 'at least one of', perhaps with added emphasis.
And that an explicit 'or' between the bullet points is added (maybe use and/or to avoid the potential interpretation as an exclusive or?).

In any case I'm content for the issue to be closed.
